" 色の設定
syntax enable
colorscheme desert
highlight Normal    guibg=NONE ctermbg=NONE
highlight NonText   guibg=NONE ctermbg=NONE
set termguicolors

" カーソルの表示
"   SI = 挿入モード
"   SR = 置き換えモード
"   EI = ノーマルモード
let &t_SI.="\e[1 q"
let &t_SR.="\e[3 q"
let &t_EI.="\e[2 q"

" インデント
set autoindent
set smartindent
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set smarttab

" 文字エンコーディング
set encoding=utf-8
" set ambiwidth=double          " 全角文字を正しく表示させたい場合、
                                " コメントアウトを解除

" 補完関連
set nocompatible

" バックアップ/スワップファイル作成
set nobackup
set noswapfile

" 行数表示
set number
set cursorline
" set relativenumber            " カーソルが置いてある行から相対的な行数を
                                " 表示させたい場合、コメントアウトを解除

" その他
set backspace=indent,eol,start  " 挿入モードでバックスペース削除を有効化
set showmatch
set mouse=a                     " エディタ内でマウスを使用可能にする
                                " (ただしコピペをする際にはmouse=に設定する必要あり)
set nohlsearch                  " 検索結果のハイライトを無効化
set incsearch                   " 検索ワードの最初の文字入力時に検索開始
set ignorecase                  " コマンドモード、キーワード検索する際に
                                " 大文字・小文字を無視
set smartcase                   " 検索内容に大文字が含まれている場合、
                                " ignorecaseを無視して大文字を優先させる
set wildignorecase
set colorcolumn=80              " 半角80文字の列に線を表示
set path=.,/usr/include/,**
set wildmenu                    " コマンドモード時に入力内容からコマンドをタブ補完
set showcmd                     " 入力中のコマンドを表示
set title                       " タイトルの追加
set backspace=indent,eol,start  " 挿入モードでbackspaceを使って削除を可能に
set list
set listchars=tab:\|-,space:_

" <Leader>キーのマッピング
let mapleader=' '             " スペースキーを<Leader>キーとしてマッピング
                                " しているが、好きなものへ再マッピングしてもOK!
                                " しかし、アルファベットや:,/,?等の
                                " ノーマルモード時に使用するものは禁止

" プラグインマネジャの自動ダウンロード
"   ダウンロード先のパス
let plug_path=has('nvim') ? stdpath('data') . '/autoload/plug.vim'
    \ : $HOME . '/.vim/autoload/plug.vim'
echo plug_path
"   ファイルが存在しない場合、ダウンロードする
if empty(glob(plug_path))
    call system(
        \ 'curl' . 
        \ ' -fLo ' . plug_path .
        \ ' --create-dirs' . 
        \ ' https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
        \ )
endif
" プラグインインストール (ここは必ず.vimrcファイル内になければならない)
" プラグインがロードされない
call plug#begin(has('nvim') ? stdpath('data') . '/plugged' : $HOME . '/.vim/plugged')
    " Tagbar (変数・関数・クラスオブジェクト等の表示)
    Plug 'preservim/tagbar'

    " LSP
    Plug 'prabirshrestha/vim-lsp'
    Plug 'mattn/vim-lsp-settings'

    " 自動補完機能
    Plug 'prabirshrestha/asyncomplete.vim'
    Plug 'prabirshrestha/asyncomplete-lsp.vim'

    " ステータスバーに表示する情報追加
    Plug 'vim-airline/vim-airline'
    Plug 'vim-airline/vim-airline-themes'

    " ファジーファインダー (fzf)
    Plug 'junegunn/fzf', { 'do': { -> fzf#install() } }
    Plug 'junegunn/fzf.vim'
call plug#end()

" PlugInstallコマンド実行していない環境下での初期動作
"   PlugInstallコマンドを実行し、プラグインをインストールする
function! s:plug_install_on_initial_launch()
    let dir=has('nvim') ? stdpath('data') . '/plugged' : $HOME . '/.vim/plugged'

    if !isdirectory(dir)
        call execute('PlugInstall')
    endif
endfunction

call s:plug_install_on_initial_launch()

" カスタムコマンド一覧: ~/.vim/after/plugin/commands.vim
" 自動実行コマンド一覧: ~/.vim/after/plugin/autocommands.vim
" 各種キーバインド一覧: ~/.vim/after/plugin/keybinds.vim
