" File tree for vim config files
"
" vim
" └── after
"     └── plugin
"         ├── airline.vim
"         ├── asyncomplete.vim
"         ├── autocommands.vim
"         ├── commands.vim
"         ├── keybinds.vim
"         ├── plugins.vim
"         └── vim_lsp.vim

" Color settings
set t_Co=256
syntax enable
colorscheme desert
set termguicolors

" Indent related
set autoindent
set smartindent
set tabstop=4
set softtabstop=4
set shiftwidth=4
set expandtab
set smarttab

" Encoding
set encoding=utf-8
" set ambiwidth=double          " If you want to correctly show double spaced
                                " characters, cancel the comment

" autocompletion related
set nocompatible

" disable backup/swapfile creation
set nobackup
set noswapfile

" show line numbers
set number
set cursorline
" set relativenumber            " If you want relative line numbers, cancel
                                " the comment

" Etc
set backspace=indent,eol,start  " Enable backspace in insert mode
set showmatch
set mouse=a                     " Enable mouse inside of vim
set nohlsearch                  " Disable highlight on search
set incsearch                   " Start search when typing keywords
set ignorecase                  " Ignore case in command and search mode
set smartcase                   " If there is upper case inside of command or search,
                                " ignore the ignorecase option
set wildignorecase
set colorcolumn=80              " Show line at 80th character
set path=.,/usr/include/,**
set wildmenu                    " Enable tab completion inside command mode
set showcmd                     " Show command when typing
set title                       " Show title
set list
set listchars=tab:\|-,space:_   " Visualize tabs and spaces

" <Leader> key mapping
let mapleader=' '               " By default, <Leader> key is mapped to space
