FROM ubuntu:focal

RUN apt-get update && apt upgrade -y
RUN apt-get install -y \
    apt-utils \
    vim

# ここ以降は必ず最後に実行
ADD vim-barebones /root/vim-barebones
WORKDIR /root/vim-barebones
RUN ./install.sh
WORKDIR /root

RUN rm -rf /root/vim-barebones
