FROM debian:buster-slim

RUN apt-get update && apt upgrade -y
RUN apt-get install -y \
    apt-utils \
    vim

# Install dependencies for LSP (Only for testing)
RUN apt-get install -y \
    clangd-11

# Run the following lines last
ADD vim-barebones /root/vim-barebones
WORKDIR /root/vim-barebones
RUN ./install.sh plugins
WORKDIR /root

RUN rm -rf /root/vim-barebones
